# Generated by Django 4.1.6 on 2023-02-12 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="choice",
            name="vote",
            field=models.IntegerField(default=0),
        ),
    ]
